problem_track/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from track import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('problem/', views.problem, name='track-problem'),
    path('problem/add/', views.ProblemCreate.as_view(), name='track-problemcreate'),
    path('problem/<int:pid>', views.problem, name='track-pid-problem'),
    path('problem/<int:pk>/update', views.ProblemUpdateView.as_view(), name='track-pk-problemupdate'),
    path('leavefeedback/<int:pid>', views.feedback, name='track-pid-leavefeedback'),
    path('feedback/<int:pk>', views.FeebackDetailView.as_view(), name='feedback-pk-detail'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.test, name='track-test')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

track/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('track.urls'))
]

track/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class ClimbingGym(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    contact = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class InternalLocation(models.Model):
    description = models.CharField(max_length=100)
    climbing_gym = models.ForeignKey(ClimbingGym, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.climbing_gym) + ':' + self.description


class Grade(models.Model):
    grade_value = models.CharField(max_length=100)

    @property
    def value(self):
        idx = self.grade_value.index('V')
        return int(self.grade_value[idx+1:])

    def __str__(self):
        return self.grade_value


class Problem(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    location = models.ForeignKey(InternalLocation, on_delete=models.SET_NULL, null=True)
    setters = models.ManyToManyField(User)
    set_date = models.DateField()
    active = models.BooleanField(default=False)
    grade = models.ForeignKey(Grade, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='images/', default='images/None/no-img.jpg')


    def get_absolute_url(self):
        return reverse('track-problem')

    def __str__(self):
        return self.name


class Rating(models.Model):
    email = models.EmailField(null=True)
    handle = models.CharField(max_length=25)
    ip = models.GenericIPAddressField(null=True)
    problem = models.ForeignKey(Problem, on_delete=models.SET_NULL, null=True)
    date_created = models.DateField(null=True)
    date_updated = models.DateField(null=True)
    rating = models.IntegerField()
    grade = models.ForeignKey(Grade, on_delete=models.SET_NULL, null=True)
    comment_text = models.TextField(max_length=300, null=True)
    visible = models.BooleanField(default=False)

    def __str__(self):
        return str(self.problem) + ':' + str(self.handle)

track/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView
from django.http import HttpResponse, Http404
from django.db.models import Count, Avg
from django.template import loader
from django import forms
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group

from .models import Problem, Rating, ClimbingGym

import datetime


class GymSelectionForm(forms.Form):
    gym = forms.ChoiceField(choices=[(x.name, x.name) for x in ClimbingGym.objects.all()])

@login_required
def problem(request, pid=None):

    if request.method == 'POST':
        form = GymSelectionForm(request.POST)
        if form.is_valid():
            probs = Problem.objects.filter(location__climbing_gym__name__contains=form.cleaned_data['gym']).annotate(
                avg_rating=Avg('rating__rating'))
    else:
        form = GymSelectionForm()
        probs = Problem.objects.annotate(avg_rating=Avg('rating__rating'))

    context = {}
    context['setter'] = Group.objects.get(name='setters') in request.user.groups.all()
    if pid is None:
        context['problems'] = probs
        context['form'] = form
        return render(request, 'track/index.html', context)

    problem = get_object_or_404(probs, pk=pid)
    context['problem'] = problem

    return render(request, 'track/problem.html', context)


class ProblemCreate(CreateView):
    model = Problem
    fields = '__all__'
    template_name = 'track/problem_create.html'


def test(request, pid=None):
    context = {}
    return render(request, 'track/test.html', context)


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['grade', 'comment_text']
    rating = forms.IntegerField(min_value=1, max_value=10)


@login_required
def feedback(request, pid):
    prob = Problem.objects.get(pk=pid)
    if request.method == 'GET':
        form = FeedbackForm()


        # get all the grades
        ratings = Rating.objects.filter(problem_id=pid)
        for rating in ratings:
            print(rating.grade.grade_value)

        context = {'form': form, 'problem': prob}
        return render(request, 'track/leavefeedback.html', context)
    else:
        # save object to db
        form = FeedbackForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            rating = Rating(email=request.user.email,
                            handle=request.user.username,
                            rating=form.cleaned_data['rating'],
                            grade=form.cleaned_data['grade'],
                            comment_text=form.cleaned_data['comment_text'],
                            date_created=datetime.datetime.now(),
                            date_updated=datetime.datetime.now(),
                            visible=True, ip=request.META.get('REMOTE_ADDR', '0.0.0.0'),
                            problem=prob)
            rating.save()

        return redirect(problem, pid)


class FeebackDetailView(DetailView):
    model = Rating
    template_name = 'track/feedback.html'

    def get_context_data(self, **kwargs):
        context = super(FeebackDetailView, self).get_context_data(**kwargs)
        return context


class ProblemUpdateView(UpdateView):
    model = Problem
    fields = '__all__'
    template_name = 'track/problem_update.html'

    def get_success_url(self, *args, **kwargs):
        return reverse('track-problem')

track/templates/track/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}<title></title>{% endblock %}
    {% load static %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'track-problem' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" href="#">Contact</a>
      </li>

    </ul>

    <span class="navbar-text">
      {% if user.is_authenticated %}
          Hello {{ user.username }},&nbsp
          <a href="/accounts/logout">Logout</a>
      {% else %}
          <a  href="/accounts/login">Login</a>
      {% endif %}
    </span>

  </div>
</nav>


{% block body %}
{% endblock body %}

{% block body_extra_js %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock body_extra_js %}
</body>

</html>

track/templates/track/feedback.html
{% extends "track/base.html" %}

{% block title %}<title>Feedback</title>{% endblock %}

{% block body %}
<a href="{% url 'track-pid-problem' rating.problem.id %}">{{ rating.problem.name }}</a>
<table class="table table-sm">
<tr><td>Email</td><td>{{ rating.email }}</td></tr>
    <tr><td>Handle</td><td>{{ rating.handle }}</td></tr>
    <tr><td>Problem</td><td>{{ rating.problem }}</td></tr>
    <tr><td>Date</td><td>{{ rating.date_created }}</td></tr>
    <tr><td>Rating</td><td>{{ rating.rating }}</td></tr>
    <tr><td>Grade</td><td>{{ rating.grade }}
    <tr><td>Comment</td><td>{{ rating.comment_text }}</td></tr>
</table>
{% endblock %}

track/templates/track/index.html
{% extends "track/base.html" %}

{% block title %}<title>Problems</title>{% endblock %}
{% block body %}
<form action="{% url 'track-problem' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% if problems %}
    <table class="table">
        <thead>
            <tr><th>name</th><th>setters</th><th>gym</th><th>location</th><th>grade</th><th>rating</th></tr>
        </thead>
        <tbody>
        {% for problem in problems %}
            {% if problem.active %}
            <tr>
                <td><a href="{% url 'track-pid-problem' problem.id %}">{{ problem.name }}</a></td  >
                <td>{{ problem.setters.all|join:", " }}</td>
                <td>{{ problem.location.climbing_gym }}</td>
                <td>{{ problem.location.description }}</td>
                <td>{{ problem.grade }}</td>
                <td>{{ problem.avg_rating }}</td>
            </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

{% endif %}
{% endblock %}

track/templates/track/leavefeedback.html
{% extends "track/base.html" %}

{% block title %}<title>Leave Feedback</title>{% endblock %}
{% block body %}
<h2>{{ problem.name }}</h2>
<form action="{% url 'track-pid-leavefeedback' problem.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

track/templates/track/problem.html
{% extends "track/base.html" %}

{% block title %}<title>Problem Details</title>{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col">
            <h2>{{ problem.name }}</h2>
            <table class="table table-sm">
                <tr><td>Description</td><td>{{ problem.description }}</td></tr>
                <tr><td>Location</td><td> {{problem.location }}</td></tr>
                <tr><td>Setters</td><td>{{ problem.setters.all|join:", " }}</td></tr>
                <tr><td>Set Date</td><td>{{ problem.set_date }}</td></tr>
                <tr><td>Grade</td><td>{{ problem.grade }}</td></tr>
                <tr><td>Rating</td><td>{{ problem.avg_rating }}</td></t></tr>
            </table>
            <a href="{% url 'track-pid-leavefeedback' problem.id %}">Feeback</a>
            <table class="table table-sms">
                <thead>
                    <tr><th>id</th><th>handle</th><th>date</th><th>rating</th><th>grade</th></tr>
                </thead>
            {% for rating in problem.rating_set.all %}
                {% if rating.visible %}
                <tr><td><a href="{% url 'feedback-pk-detail' rating.id %}">{{ rating.id }}</a></td>
                        <td>{{ rating.handle|default:None }}</td>
                        <td>{{ rating.date_created }}</td>
                        <td>{{ rating.rating }} </td>
                        <td>{{ rating.grade }}</td></tr>
                {% endif %}
            {% endfor %}
            </table>
        </div>
        <div class="col">
            <img src="{{ problem.image.url }}" alt="{{ problem.image.name }}" style="width:512px"/>
        </div>
    </div>
</div>
{% endblock %}

track/templates/track/problem_create.html
{% extends "track/base.html" %}

{% block title %}<title>Create Problem</title>{% endblock %}

{% block body %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

track/templates/track/problem_update.html
{% extends "track/base.html" %}

{% block title %}<title>Update Problem</title>{% endblock %}

{% block body %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock %}

track/templates/track/test.html
{% extends "track/base.html" %}

{% block title %}<title>Test</title>{% endblock %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-sm">
      One of three columns
    </div>
    <div class="col-sm">
      One of three columns
    </div>
    <div class="col-sm">
      One of three columns
    </div>
  </div>
</div>
{% endblock %}